<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StartupObject>Gravo.GravoCmd</StartupObject>
    <RootNamespace>Gravo</RootNamespace>
    <AssemblyName>Gravo-Cmd</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <OptionStrict>On</OptionStrict>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GravoCore\GravoCore.vbproj" />
  </ItemGroup>

</Project>
