<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GravoApp.Desktop</RootNamespace>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GravoApp\GravoApp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\languages.s3db" Link="languages.s3db" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
