name: .NET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build with dotnet
      run: dotnet build GravoCore -c Release
    - name: Unit Tests
      run: dotnet test GravoCore.UnitTests -c Release --collect:"XPlat Code Coverage" --results-directory TestResults
    - name: Coverage report
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.5.10
        reportgenerator -reports:"TestResults/**/coverage.cobertura.xml" -targetdir:coverage-report "-reporttypes:Html;MarkdownSummaryGithub"
        cat coverage-report/SummaryGithub.md >> "$GITHUB_STEP_SUMMARY"
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage-report
